### ISSUE TITLE
Feature: disable auto close if someone is nearby

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis#157] opened 2022-05-07 09:47 UTC
Disable closing auto close for stargate if someone go through and there is person nearby. I think it can be added as optional setting in the config with the value **true or false.**

**Comment by MR-Spagetty** [comment] 2022-05-07 09:50
Do not assign people to your "issue" the purpose of assigning somebody to the issue is not to get their attention it is for those whom maintain the repository to say who will be working on an issue if it is to get worked on

**Comment by MR-Spagetty** [comment] 2022-05-07 09:51
also this is a duplicate of #156

**Comment by lukasz4444** [comment] 2022-05-07 09:54
first i don even know what is assign on the github it just happen but sorry

second here i am talking about disabling it if someone is nearby not #156 because there i talk about setting radius

**Comment by MineDragonCZ** [comment] 2022-05-07 10:00
> Do not assign people to your "issue" the purpose of assigning somebody to the issue is not to get their attention it is for those whom maintain the repository to say who will be working on an issue if it is to get worked on

Assign is automatic

**Comment by MR-Spagetty** [comment] 2022-05-07 10:01
i don't think i haev ever seen an issue get automatically assigned before adn it does specifically state that Lukass assigned you ~ a minute after creating teh issue

**Closed** 2022-05-07 10:00 UTC
Labels: Will not be fixed/added, Duplicate, Enhancement

**Comment by MR-Spagetty** [comment] 2022-05-07 10:04
nvm it appears that it does automatically assign teh issue to you however i don't think that it does it by default and that it must be setup to do so
